import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";
import ServiceWorkerRegister from "./sw-register";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const description =
  "Score counter for card games like 500, Piratbridge and Gabong.";

// Base URL for absolute metadata URLs (e.g. the link-preview image). Uses the
// Vercel production domain when deployed, falls back to localhost in dev. Set
// NEXT_PUBLIC_SITE_URL to override with a custom domain.
const siteUrl =
  process.env.NEXT_PUBLIC_SITE_URL ||
  (process.env.VERCEL_PROJECT_PRODUCTION_URL
    ? `https://${process.env.VERCEL_PROJECT_PRODUCTION_URL}`
    : "http://localhost:3000");

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: "Games Counter",
  description,
  applicationName: "Games Counter",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Games Counter",
  },
  icons: {
    icon: "/icons/icon-192.png",
    apple: "/icons/apple-icon.png",
  },
  // Link-preview (unfurl) metadata. The image itself is generated by
  // opengraph-image.tsx / twitter-image.tsx and injected automatically.
  openGraph: {
    type: "website",
    siteName: "Games Counter",
    title: "Games Counter",
    description,
  },
  twitter: {
    card: "summary_large_image",
    title: "Games Counter",
    description,
  },
};

export const viewport: Viewport = {
  themeColor: "#063e20",
  width: "device-width",
  initialScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ServiceWorkerRegister />
        <Analytics />
      </body>
    </html>
  );
}
